class AppString {
  static String appname = "SMedical",
      bestDocapp = "Best Doctor\n Appointment App",
      welcome = "Welcome ",
      weAreExcuited = "We are happy to have you back",
      signupNow = "Signup now and start exploring all",
      email = "Email",
      emailHint = "Enter your email ",
      password = "Password",
      passwordHint = "Enter your password",
      fullName = "Full name",
      fullnameHint = "Enter your full name",
      confirmPassword = "Confirm password",
      login = "Login",
      signup = "Signup",
      search = "Search doctor",
      alreadyHaveAccount = "Already have an account !",
      body = "Body",
      ear = "Ear",
      liver = "Liver",
      lungs = "Lungs",
      heart = "Heart",
      kidny = "Kidny",
      eye = "Eye",
      stomac = "Stomac",
      tooth = "Tooth",
      dontHaveAccount = "Don't have an account";
}
