export './colors.dart';
export './fonts.dart';
export './images.dart';
export './strings.dart';
export 'package:flutter/material.dart';
export 'package:velocity_x/velocity_x.dart';
export 'package:get/get.dart';
export 'package:firebase_auth/firebase_auth.dart';
export 'package:cloud_firestore/cloud_firestore.dart';
